Creates assessment entity
AY2122S2-CS2103T-T13-2/tp pull request #122
Opened 2022-03-22 16:28 UTC by lkldev

closes #116 

This PR creates the assessment entity and update the code to support this new entity. 
modifications made:
* Update parser to parse assessment entity
* Update Add, Delete and List command to support assessment entity
* Update SampleDataUtil to create sample assessments

Todos:
* update UI to support assessment entity
* update storage to save assessments

2022-03-23 03:25 UTC, jxt00 commented on src/main/java/seedu/address/model/assessment/exceptions/AssessmentNotFoundException.java
> + * Signals that the operation is unable to find the specified module.
`module` change to `Assessment`?

2022-03-23 03:25 UTC, jxt00 commented on src/main/java/seedu/address/model/assessment/exceptions/DuplicateAssessmentException.java
> + * Signals that the operation will result in duplicate Modules (Modules are considered duplicates if they have the same
`Modules` change to `Assessments`?

2022-03-23 03:27 UTC, jxt00 commented on src/main/java/seedu/address/model/assessment/SimpleName.java
> +     * Returns true if a given string is a valid module name.
`module name` should be `simple name`?

2022-03-23 03:27 UTC, jxt00 commented on src/main/java/seedu/address/model/assessment/SimpleName.java
> +     * The first character of the Module Name must not be a whitespace,
`Module Name` should be `Simple Name`?

2022-03-23 06:27 UTC, lkldev commented on src/main/java/seedu/address/model/assessment/exceptions/DuplicateAssessmentException.java
> + * Signals that the operation will result in duplicate Modules (Modules are considered duplicates if they have the same
Resolved in latest commit

2022-03-23 06:27 UTC, lkldev commented on src/main/java/seedu/address/model/assessment/exceptions/AssessmentNotFoundException.java
> + * Signals that the operation is unable to find the specified module.
Resolved in latest commit

2022-03-23 06:27 UTC, lkldev commented on src/main/java/seedu/address/model/assessment/SimpleName.java
> +     * Returns true if a given string is a valid module name.
Resolved in latest commit

2022-03-23 06:27 UTC, lkldev commented on src/main/java/seedu/address/model/assessment/SimpleName.java
> +     * The first character of the Module Name must not be a whitespace,
Resolved in latest commit

2022-03-23 06:37 UTC, jxt00 approved these changes
LGTM 🔥

2022-03-24 18:15 UTC, wxliong requested changes
Looks good! Just a few minor changes to be made :)

2022-03-24 18:15 UTC, wxliong commented on src/main/java/seedu/address/model/TAssist.java
> +     * Returns true if a assessment with the same identity as {@code assessment} exists in the TAssist.
minor typo, should be an instead of a

2022-03-24 18:15 UTC, wxliong commented on src/main/java/seedu/address/model/assessment/Assessment.java
> +                && otherAssessment.getSimpleName().equals(getSimpleName());
repeated code

2022-03-24 18:15 UTC, wxliong commented on src/main/java/seedu/address/model/assessment/Assessment.java
> +                builder.append("; Simple name: ")
minor typo, `Simple name` should be `Simple Name`

2022-03-25 06:26 UTC, lkldev commented on src/main/java/seedu/address/model/TAssist.java
> +     * Returns true if a assessment with the same identity as {@code assessment} exists in the TAssist.
resolved in latest commit

2022-03-25 06:26 UTC, lkldev commented on src/main/java/seedu/address/model/assessment/Assessment.java
> +                && otherAssessment.getSimpleName().equals(getSimpleName());
resolved in latest commit

2022-03-25 06:27 UTC, lkldev commented on src/main/java/seedu/address/model/assessment/Assessment.java
> +                builder.append("; Simple name: ")
resolved in latest commit

2022-03-25 10:25 UTC, wxliong approved these changes
LGTM! :)

2022-03-25 10:26 UTC, merged